[package]
org = "Ramith"
name = "nadacdata"
version = "1.0.0"
export = ["nadacdata"]
distribution = "2201.6.0"
keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
icon = "docs/icon.png"

[build-options]
observabilityIncluded = true
